# A sample Gemfile
source "https://rubygems.org"
gem "whenever"
gem "net-ldap"
gem "paperclip"
gem "rake"
gem "rails", "3.0.12"
gem "mysql2", "0.2.18"
gem "rdoc"
gem "rubycas-client-rails"
gem "rubycas-client", "2.2.1"
gem "rails-settings", :git => "git://github.com/100hz/rails-settings.git"
gem "pry"
gem "pry-rails"
gem "dynamic_form"
gem "permanent_records", "~> 2.1.2"
gem "nilify_blanks"
gem "mail", "2.2.19"
gem "ffaker"
