development: &default
  adapter: mysql2
  database: <%= ENV.fetch("RES_DB_NAME_DEV","") %>
  host: <%= ENV['RES_DB_HOST'] %>
  encoding: utf8
  min_messages: warning
  pool: <%= Integer(ENV.fetch("DB_POOL", 5)) %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
  timeout: 5000
  username: <%= ENV.fetch("RES_DB_USERNAME", "") %>
  password: <%= ENV.fetch("RES_DB_PASSWORD", "") %>

test:
  <<: *default
  database: <%= ENV.fetch("RES_DB_NAME_TST","") %>

production: &deploy
  adapter: mysql2
  database: <%= ENV.fetch("RES_DB_NAME_PRD","") %>
  encoding: utf8
  min_messages: warning
  pool: <%= [Integer(ENV.fetch("MAX_THREADS", 5)), Integer(ENV.fetch("DB_POOL", 5))].max %>
  timeout: 5000
  url:  <%= ENV.fetch("DATABASE_URL","") %>
